name: "Default Workflow (main)"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-terraform-apply:
    uses: ./.github/workflows/terraform-apply.yml
    permissions:
      contents: read
    secrets: inherit
  run-terraform-linter:
    needs: [run-terraform-apply]
    uses: ./.github/workflows/terraform-linter.yml
    permissions:
      contents: read
