name: "Default Workflow (main)"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    run-terraform-apply:
        uses: ./.github/workflows/terraform-apply.yml
        permissions:
            contents: read
        secrets: inherit